background = #0c0018
foreground = #00f5ff
cursor-color = #00f5ff
selection-background = #ff0099
selection-foreground = #0c0018
bold-color = #ff33cc
font-thicken = false
minimum-contrast = 1
config-file = ?"~/.local/state/omarchy/neonfx/ghostty-shaders.conf"

palette = 0=#1a1030
palette = 1=#ff3366
palette = 2=#00ff9f
palette = 3=#ffb347
palette = 4=#5eb3ff
palette = 5=#ff0099
palette = 6=#00f5ff
palette = 7=#00f5ff
palette = 8=#3d2a5c
palette = 9=#ff5c7a
palette = 10=#33ffb8
palette = 11=#ffe066
palette = 12=#7ec4ff
palette = 13=#ff33aa
palette = 14=#66faff
palette = 15=#66faff
