$activeBorderColor = rgba(00f5ffff) rgba(ff0099ff) 45deg
$inactiveBorderColor = rgba(6a30a088)
$activeShadowColor = rgba(ff0099dd)
$inactiveShadowColor = rgba(00f5ff44)
$cyanGlow = rgba(00f5ff88)

general {
    border_size = 3

    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}

decoration {
    blur {
        size = 5
        passes = 4
        special = true
        brightness = 0.72
        contrast = 0.88
    }

    shadow {
        enabled = true
        range = 28
        render_power = 10
        color = $activeShadowColor
        color_inactive = $inactiveShadowColor
    }
}
