# Hyprlock — NeonFX

$color = rgba(12,0,24,1.0)
$inner_color = rgba(12,0,24,0.75)
$outer_color = rgba(0,245,255,1.0)
$font_color = rgba(236,230,255,1.0)
$placeholder_color = rgba(236,230,255,0.65)
$check_color = rgba(255,0,153,1.0)
